baseurl = "https://blog.heliomedeiros.com/"
defaultContentLanguage = "en"
title = "helio."
theme = "beautifulhugo"

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    title = "helio."
    weight = 1
    contentDir = "content/en"
    [[languages.en.menu.main]]
      name = "Posts"
      url = "/"
      weight = 1

  [languages.pt]
    languageCode = "pt-br"
    languageName = "Português"
    title = "helio."
    weight = 2
    contentDir = "content/pt"
    [[languages.pt.menu.main]]
      name = "Posts"
      url = "/"
      weight = 1

[pagination]
  pagerSize = 50

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  subtitle = "Technology insights and agile development"
  comments = false
  disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    codeFences = true
    guessSyntax = true

# Analytics Configuration for Blog Only
[services]
  [services.googleAnalytics]
    id = "G-GL0Q1PNV4W"
