baseurl = "https://blog.heliomedeiros.com/"
defaultContentLanguage = "en"
title = "helio."
theme = "beautifulhugo"

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    title = "helio."
    weight = 1
    contentDir = "content/en"

  [languages.pt]
    languageCode = "pt-br"
    languageName = "Português"
    title = "helio."
    weight = 2
    contentDir = "content/pt"

[pagination]
  pagerSize = 50

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  subtitle = "Technology insights and agile development"
  comments = false
  disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    codeFences = true
    guessSyntax = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
